disabled_rules:
- force_try
- identifier_name
- line_length
- file_length
- cyclomatic_complexity
- type_body_length
- function_body_length
- trailing_whitespace
- function_parameter_count
- force_cast

excluded:
- katatrainTests
- katatrainUITests
